### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by Tschaeaen** [Blacktiger21/Musikbot-Installer-for-Ubuntu-und-Debian#1]
Wenn ich den Bot mit "./start.sh" starten möchte dann kommt bei mir: "./start.sh: line 80: syntax error: unexpected end of file"

**Comment by Blacktiger21** [comment]
Mein fehler wird gleich gefixt 👍 :)

**Comment by Blacktiger21** [comment]
Behoben müsste jetzt gehen habe nur nen fi falsch gesetzt 👍

**Comment by Tschaeaen** [comment]
Ja funktioniert.
